### ISSUE TITLE
Transaction execution failed,Exceeded the prepaid gas

### ISSUE THREAD

**Issue by lk2684753** [near-apps/nft-series#1]
When I execute NFT Mint with a script, I generate a lot of NFT tokens; (There are probably dozens)
When I call nft_approve, the transaction fails (the script is executed in batches and the token ID of the owner is iterated).
When I transfer one of the tokens to another account, there is no problem with the call;
I wonder if it is because my account has cast a large number of tokens. Excluding environmental problems, there will be problems when I import my account to other machines.
The main error is that the gas fee is too high, but this is the problem when I set any gas value.
![9720519f5284796d63e3c743629a224](https://user-images.githubusercontent.com/42611777/134878407-d1e741f0-36f2-4c1c-978b-a35c7027a570.png)
![bc8ebf3b8cf21a1551a85726c4adebe](https://user-images.githubusercontent.com/42611777/134878449-a6afd4a4-3269-4707-9af7-bae8a3f823db.png)
![55cb4472a99ad59b82dd969a4aa8ae6](https://user-images.githubusercontent.com/42611777/134878478-46002b60-0805-42ec-8a8f-5852ab3078a8.png)

**Comment by mattlockyer** [comment]
FWIW these screenshots don't tell anybody much. **You need to paste in links to the explorer where the transaction failed and your contract source.**

I had to type this by hand...
https://explorer.testnet.near.org/accounts/dev-1632724418776-68219858133201

Notice your contract bytes are:
486552

Here's bytes from a contract from this repository with no modifications:
379341

What is the smart contract you are using?

The tests from a contract in this repository can be seen here as well, the nft_approve has always been passing:
https://explorer.testnet.near.org/accounts/dev-1632748378366-85849636115246

I am not sure what contracts you are using but I suspect your problem comes from here:

https://github.com/near/near-sdk-rs/blob/d99f30175720d06331d7747dbc1a59cc0e66b3ff/near-contract-standards/src/non_fungible_token/approval/approval_impl.rs#L79

The const:
https://github.com/near/near-sdk-rs/blob/d99f30175720d06331d7747dbc1a59cc0e66b3ff/near-contract-standards/src/non_fungible_token/approval/approval_impl.rs#L12

is only 10 Tgas.

Which means the function nft_approve can only do so much computation.

I'll keep looking, but a link to your contract would be helpful.

**Comment by mattlockyer** [comment]
Yes this is the cause. Stay tuned for a further breakdown.

**Comment by mattlockyer** [comment]
This works:
https://github.com/mattlockyer/near-sdk-rs/commit/b68ac0be451af17899de9a069d24212073de77f5

With the following test, which attempts to call nft_approve 10 times (the first 9 fail on purpose due to sale args being incorrect, but the 10th succeeds):
![image](https://user-images.githubusercontent.com/321340/134923919-659fabb5-c811-42eb-a223-e94692c392e5.png)

You can check the failures from before were due to exceeded gas (even with correct sale args):
https://explorer.testnet.near.org/transactions/96Mc921gSZiBYhLUhSbaR6E4f76RUq48PW7VGq2bTAGU

The failures after the above commit are due to sale args being incorrect:
https://explorer.testnet.near.org/transactions/C1TesBjGV4LnznRZbWvugcRBkQRMM8RtPf3nRymS8TCH

**Comment by mattlockyer** [comment]
I will follow up and get the standard / near-examples updated shortly.
